[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
usdf_swap = "USDFmFa553nkGNSvFn2gXCnpPuWLkgre2aHmPMDyaWi"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "~/.config/solana/id.json"
cluster = "http://127.0.0.1:8899"

[scripts]
test = "echo \"Error: no test specified\" && exit 1"
